### PR TITLE
Consolidate operations

### PR DESCRIPTION
**Pull request by bandrel**
Implementation of the issue #34

### CODE REVIEW

**Comment by ryman1** [comment]
this doesn't cover the other file writing operations that can be performed.

**Comment by bandrel** [comment]
Please review and test

**Comment by ryman1** [comment]
Not yet sure if it's a new bug or not, but I'm finding that "modern" is always running even when a different operation is specified. Edit: this issue exists in the master branch. Opened issue https://github.com/BlackBox-CSP/password-tools/issues/39

Also, the there's an extra file being output that doesn't include a prefix

results from cracked_hash_stats.py -C -U tttcracked -s tttshared (removed):

```
ls *ttt* -l
-rw-rw-r-- 1 gpu gpu 178505 Feb 15 13:56 Combined-tttcracked
-rw-rw-r-- 1 gpu gpu 205685 Feb 15 13:56 Combined-tttshared
-rw-rw-r-- 1 gpu gpu 178505 Feb 15 13:56 Modern-tttcracked
-rw-rw-r-- 1 gpu gpu 205685 Feb 15 13:56 Modern-tttshared
-rw-rw-r-- 1 gpu gpu      0 Feb 15 13:56 tttcracked
```

**Comment by ryman1** [comment]
Fixed the extra output file issue. @bandrel see if you agree with the changes in c976c8200e6f0e9843d2e0264cb2899efbb2c78f

**Comment by bandrel** [comment]
I'm good.

**Pull request merged**
